version: '3'
services:
  mysql:
    restart: always
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 23people
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "6033:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 20s
      retries: 10


  app:
    restart: on-failure
    build: '.'
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - mysql